### ISSUE TITLE
Post Initial Release Todo

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/intellij-plugin-save-actions#9]
- [x] Get plugin approved
- [x] Get someone for cross reviewing
- [x] Beta test
- [x] Replace plugin in all existing projects (on GitHub + internal)
  - [x] GitHub
  - [x] internal
  - [x] Maybe a short blog post?

**Comment by AB-xdev** [comment]
Internal Beta test successful concluded after a week.
No negative feedback or bugs encountered.
